### ISSUE TITLE
Add static/* to .gitignore?

### ISSUE THREAD

**Issue by khipkin** [rit-csc/CSCWebsite#1]
It seems silly to version-control stuff that should be automatically pulled from staticfiles/\* every time staticfiles/\* is updated. @RaineForest, thoughts?

**Comment by chrissprague** [comment]
problem is addressed (add `static/` to gitignore) @ https://github.com/rit-csc/CSCWebsite/commit/022b506fa82297450bc4a9d6839b42953345dc05

static files untracked @ https://github.com/rit-csc/CSCWebsite/commit/1095603daec7f673e1703a7d730f9acfd4b7a354

don't want to close this issue just yet though because this hasn't been merged into production yet, plus the amount of files I removed is daunting, so there's that

**Comment by khipkin** [comment]
@chrissprague, Nice! Thanks.

I think this should remain open until we have a more reliable way to automatically collect the static files when the live site is updated.  Right now, the `collectstatic` thing does nothing if the static/ folder already exists; instead, it should overwrite the changed files.

@RaineForest, maybe we could accomplish this with a git hook?

**Comment by chrissprague** [comment]
@khipkin a `cronjob` might work too, like run `collectstatic` twice a day or something. Though I guess a hook would make more sense if we're only going to be updating `staticfiles/` via merges on live

**Comment by khipkin** [comment]
@chrissprague, we only need to update the static files when there's a change, which would only happen when we update the live site.  That's why I suggested a hook.

Also, it wouldn't need to just call `collectstatic`; as stated above, that call doesn't do anything if the static folder already exists.  We would first have to delete the folder and its contents, and then call `collectstatic`.  Hypothetically, this should be relatively easy to accomplish. :)

**Comment by khipkin** [comment]
@RaineForest any progress on this? or thoughts? I can try to work on this, but I want to know if you have anything to say on the matter beforehand.

**Comment by RaineForest** [comment]
I guess it's fine, I'll just write a script on the server so I remember to do it every time.

**Comment by RaineForest** [comment]
Script written, on live server only (not in repo).

**Comment by chrissprague** [comment]
@RaineForest what kind of script is it? Can we get it in the repo? :cactus:

**Comment by RaineForest** [comment]
It's a bash script. I'd rather not have it in the repo, since it's only website maintenance and not really pertaining to the website itself.

**Comment by chrissprague** [comment]
@RaineForest but do you run it on a cronjob or something?

**Comment by RaineForest** [comment]
No, why? We'll only need to run it when something is pushed to master, not every 5 minutes or so.

**Comment by chrissprague** [comment]
@RaineForest so it's a hook? and cronjobs can be run at any time interval (past a minute or so.) doesn't necessarily need to be every 5m :hamster:

**Comment by RaineForest** [comment]
No, it's just a script. I run it manually when we push to master, when we decide that there are updates to be made to live.
