### ISSUE TITLE
"View Project on GitHub" for website

### ISSUE THREAD

**Issue by chrissprague** [rit-csc/CSCWebsite#10]
We should have a link on the website to the GitHub repository which holds the code behind the website.

I think it makes sense that if people are checking out our website, we should refer them to this repo from the site in some way, even if it's just another link on the "Projects" page. I think a little link (perhaps something in the footer?) should be made available on every page for that matter, imo.

**Comment by khipkin** [comment]
@chrissprague this is already part of the github-api branch.

**Comment by chrissprague** [comment]
@khipkin oh, whoops. Nice.
