### ISSUE TITLE
minor formatting issue in projects page with longer repo/project names

### ISSUE THREAD

**Issue by chrissprague** [rit-csc/CSCWebsite#16]
![screenshot example of problem](https://cloud.githubusercontent.com/assets/3145878/7075739/5196567a-ded2-11e4-97d8-81ef3cc6153f.png)

Not sure if this is how we want it to look. I think the language of the project perhaps should be scooted more over to the right so we don't have this awkward word-wrap issue.

Thoughts?

**Comment by YawarRaza7349** [comment]
I think it should be pushed as right as possible, maybe even flushed right.

**Comment by chrissprague** [comment]
That would make sense. Shouldn't be hard to implement either.

**Comment by khipkin** [comment]
Fixed in commit 802122ba8eab3aa84363faf43c22e0cef08c560d.

![image](https://cloud.githubusercontent.com/assets/5641207/7082759/d0ffa340-df0d-11e4-97c9-6a3e70de64ae.png)

If you guys like how that looks, go ahead and merge into staging/master. :)

**Comment by chrissprague** [comment]
@khipkin Looks exactly like what Yawar described. Nice work! :+1:

However, since the fix has not been merged to live, I think this bug should remain open until then.

Also, was this fix done in a tb? If so, can you make a pull request for it?

**Comment by chrissprague** [comment]
@khipkin I think we should keep the bugs open until the fixes are merged into master. This merge was just into staging. :womans_hat:

**Comment by RaineForest** [comment]
It's into master
