### ISSUE TITLE
Remove hard coded SECRET_KEY from settings.py

### ISSUE THREAD

**Issue by RaineForest** [rit-csc/CSCWebsite#27]
[Here](https://github.com/rit-csc/CSCWebsite/blob/staging/csc_new/csc_new/settings.py#L28).  Should have been done for a while. Instead of having it as a constant in settings.py (which isn't an issue right now, because the live site has a different key than what's in the file now), it should read the key in from a file WHICH ISN'T TRACKED BY THE REPOSITORY (important part).

**Comment by chrissprague** [comment]
Why is this an issue? Like, don't we need a key to run the server on development? And as you said, the one we do use isn't tracked in the repository

**Comment by RaineForest** [comment]
Two things:
1. If there are changes that need to be applied to settings.py, it might cause a conflict on live, because of [this](https://github.com/rit-csc/CSCWebsite/issues/1#issuecomment-91573623).  This would allieviate that problem.
2. Security: we're doing it wrong.  This becomes a bigger issue once membership and sign-ins are in the site, so it's future proofing now for future E-Boards about something that they might not catch.

Yeah, we need a key; I'm not saying we don't.  It's that the key needs to not be in the source.  Reading the key in from a file when settings.py is run by the server (whenever that is) would keep the key out of the source as well as not needing to stash-pull-pop settings.py on live whenever there's a change to live.

**Comment by khipkin** [comment]
Sounds good, @RaineForest .  :+1: Can you update the README when you make this change?

**Comment by zg** [comment]
`settings.py` is ignored through `.gitignore`, and I removed the file from the repo via rit-csc/CSCWebsite@ce00a7dc182e356f66a6c33f773298163ced65c0

**Comment by RaineForest** [comment]
Test your code before you make a commit.  `settings.py` is needed to store config files about the webserver.  The reason it's being ignored is to not have people accidentally push with debug on, which then gets pushed to live with debug on, resulting in debug messages on a live website, which isn't too professional.

**Comment by RaineForest** [comment]
Live server uses a different key, and settings.py is ignored in live server update. I did this a while ago, but I guess I forgot to close the issue. Whoops!
