### ISSUE TITLE
Migrate Trello issues onto GitHub issues

### ISSUE THREAD

**Issue by chrissprague** [rit-csc/CSCWebsite#3]
Now that GitHub will work for keeping track of our website.

**Comment by khipkin** [comment]
This looks like more of a Chris-TODO than a GitHub issue.

**Comment by chrissprague** [comment]
@khipkin Good point, though technically anyone could do this. Either way, perfect for the [invalid](https://github.com/rit-csc/CSCWebsite/labels/invalid) label!
