### ISSUE TITLE
Issue running the server

### ISSUE THREAD

**Issue by zg** [rit-csc/CSCWebsite#30]
```
$ python3 manage.py test
Creating test database for alias 'default'...
CommandError: One or more models did not validate:
auth.user: Accessor for m2m field 'groups' clashes with related m2m field 'Group.user_set'. Add a related_name argument to the definition for 'groups'.
auth.user: Accessor for m2m field 'user_permissions' clashes with related m2m field 'Permission.user_set'. Add a related_name argument to the definition for 'user_permissions'.
```

**Comment by zg** [comment]
Uncommenting [line 22 in `settings.py`](https://github.com/rit-csc/CSCWebsite/blob/staging/csc_new/csc_new/settings.py#L22) results in:

```
$ py3 manage.py test
Creating test database for alias 'default'...
CommandError: One or more models did not validate:
admin.logentry: 'user' has a relation with model <class 'member.models.Member'>, which has either not been installed or is abstract.
auth.user: Model has been swapped out for 'member.Member' which has not been installed or is abstract.
```

**Comment by khipkin** [comment]
Stems from commit 9608ce7f31fdd6f7aaba93a74b052d5f7fa51df8

**Comment by khipkin** [comment]
@zg this is fixed, correct? If so, please create a pull request with the fix and close this issue when it gets merged to staging.

**Comment by zg** [comment]
It's just a lack of documentation specifying that you need to uncomment some lines in the `settings.py` file. I'll update README.md in a pull request to specify this when trying to run the server.

Referencing to the commit: rit-csc/CSCWebsite@b522922e087528a426c5a09f9f09e0787263b973

**Comment by zg** [comment]
rit-csc/CSCWebsite@b522922e087528a426c5a09f9f09e0787263b973
